apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vulnerable-log4j-puller
  namespace: vulnerable-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: vulnerable-log4j
- kind: ServiceAccount
  name: pipeline
  namespace: vulnerable-cicd
- kind: ServiceAccount
  name: default
  namespace: exploitkit-log4j
