version: 1

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
  EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest"
  EE_BUILDER_IMAGE: "registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8:latest"

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
