---
- hosts: aap-demoeda-target*
  gather_facts: true

  tasks:

    - name: Set Targets IP lists
      ansible.builtin.set_fact:
        target_ip_list: "{{ ansible_play_hosts|
                            map('extract', hostvars, 'ansible_all_ipv4_addresses')|
                            map('first')|list }}"

- hosts: aap-demoeda-sup.rhntnx.hpecic.net
  gather_facts: false
  collections:
    - community.grafana
    - prometheus.prometheus
  vars:
    - grafana_password: 'admin'

  tasks:

    - name: Set Targets IP lists from first play
      ansible.builtin.set_fact:
        target_ip_list_global: "{{ hostvars['aap-demoeda-target-0.rhntnx.hpecic.net']['target_ip_list'] }}"

    - debug: 
        var: target_ip_list_global

    - name: Create promethues data source
      community.grafana.grafana_datasource:
        name: Prometheus-Data
        grafana_url: http://localhost:3000
        grafana_user: admin
        grafana_password: "{{ grafana_password }}"
        ds_type: prometheus
        ds_url: http://localhost:9090

    - name: Import Grafana dashboard
      community.grafana.grafana_dashboard:
        grafana_url: http://localhost:3000
        grafana_user: admin
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        overwrite: true
        path: https://raw.githubusercontent.com/davmartini/redhat-techs/main/ansible/eda/templates/node-exporter-for-prometheus-dashboard.json


    - name: Configure prometheus from template
      ansible.builtin.template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus

    - name: Reload prometheus service
      ansible.builtin.service:
        name: prometheus
        state: restarted

