---
- hosts: aap-demoeda-sup.rhntnx.hpecic.net
  gather_facts: false
  collections:
    - community.grafana
    - prometheus.prometheus
  vars:
    - grafana_password: 'redhat'

  tasks:

    - name: Change grafan admin password
      community.grafana.grafana_user:
        url: http://localhost:3000
        login: admin
        password: "{{ grafana_password }}"
        name: dmartini
        email: dmartini@redhat.com

    - name: Create promethues data source
      community.grafana.grafana_datasource:
        name: Prometheus-Data
        grafana_url: http://localhost:3000
        grafana_user: admin
        grafana_password: admin
        ds_type: prometheus
        ds_url: http://localhost:9090