---
- hosts: aap-demoeda-target*
  gather_facts: yes

  tasks:
  
    - name: Set Targets IP lists
      ansible.builtin.set_fact:
        - target_ip_list: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Print ip list
      ansible.builtin.debug:
        var: target_ip_list

- hosts: aap-demoeda-sup.rhntnx.hpecic.net
  gather_facts: false
  collections:
    - community.grafana
    - prometheus.prometheus
  vars:
    - grafana_password: 'redhat'

  tasks:

    - name: Create promethues data source
      community.grafana.grafana_datasource:
        name: Prometheus-Data
        grafana_url: http://localhost:3000
        grafana_user: admin
        grafana_password: "{{ grafana_password }}"
        ds_type: prometheus
        ds_url: http://localhost:9090

    - name: Import Grafana dashboard
      community.grafana.grafana_dashboard:
        grafana_url: http://localhost:3000
        grafana_user: admin
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        path: https://raw.githubusercontent.com/davmartini/redhat-techs/main/ansible/eda/templates/node-exporter-for-prometheus-dashboard.json