---
- name: delete Nutanix VMs for EDA environment
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: false

  tasks:

    - name: Get aap-demoeda-sup VM facts
      nutanix.ncp.ntnx_vms_info:
        filter:
         vm_name: "aap-demoeda-sup"
      register: vms_sup     

    - name: Set vms sup uuid
      ansible.builtin.set_fact:
        uuid_vms_sup: "{{ vms_sup.response | json_query('entities[*].metadata.uuid') }}"

    - name: Print VMs sup
      ansible.builtin.debug:
        var: uuid_vms_sup

    - name: Delete aap-demoeda-sup VMs
      nutanix.ncp.ntnx_vms:
        state: absent
        vm_uuid: "{{ item }}"
      loop: "{{ uuid_vms_sup }}"
      register: vms_delete_sup
      when: uuid_vms_sup | length > 0

    - name: Get aap-demoeda-target VM facts
      nutanix.ncp.ntnx_vms_info:
        filter:
         vm_name: "aap-demoeda-target.*"
      register: vms_target

    - name: Set vms target uuid
      ansible.builtin.set_fact:
        uuid_vms_target: "{{ vms_target.response | json_query('entities[*].metadata.uuid') }}"

    - name: Print VMs target
      ansible.builtin.debug:
        var: uuid_vms_target

    - name: Delete EDA target VMs
      nutanix.ncp.ntnx_vms:
        state: absent
        vm_uuid: "{{ item }}"
      loop: "{{ uuid_vms_target }}"
      register: vms_delete_target
      when: uuid_vms_target | length > 0        