---
- name: Deploy packages on SUP servers
  hosts: aap-demoeda-sup.rhntnx.hpecic.net
  gather_facts: true
  vars:
    - prometheus_url: 'https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz'

  tasks:

    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present
 
    - name: Add prometheus user to prometheus group
      ansible.builtin.user:
        name: prometheus
        groups: prometheus
        shell: /bin/bash
        state: present

    - name: Create prometheus data directory
      ansible.builtin.file:
        path: /opt/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Create prometheus conf directory
      ansible.builtin.file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Download Prometheus binarie
      ansible.builtin.get_url:
        url: "{{ prometheus_url }}"
        dest: /tmp/prometheus.tar.gz
        mode: '0440'
        owner: prometheus
        group: prometheus

    - name: Extract Prometheus binarie to tmp directory
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Rename Prometheus directory
      ansible.builtin.shell: mv /tmp/prometheus-* /tmp/prometheus

    - name: Copy prometheus binaries to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/prometheus/{{ item }}
        dest: /usr/local/bin/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'
      loop:
        - prometheus
        - promtool

    - name: Copy prometheus configuration file to /etc/prometheus
      ansible.builtin.copy:
        src: /tmp/prometheus/{{ item }}
        dest: /etc/prometheus/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'
      loop:
        - consoles
        - console_libraries

    - name: Copy prometheus config file
      ansible.builtin.copy:
        src: "templates/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Copy prometheus service file
      ansible.builtin.copy:
        src: templates/prometheus.service
        dest: /etc/systemd/system/
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Enable and start prometheus service
      ansible.builtin.service:
        name: prometheus
        state: started
        enabled: true

    - name: Delete temporary prometheus files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/prometheus
        - /tmp/prometheus.tar.gz

    - name: Import Grafana GPG Key
      ansible.builtin.rpm_key:
        state: present
        key: https://rpm.grafana.com/gpg.key

    - name: Create Grafana YUM repo
      ansible.builtin.yum_repository:
        name: grafana
        description: Grafana repo
        baseurl: https://rpm.grafana.com
        gpgkey: https://rpm.grafana.com/gpg.key
        exclude:
          - '*beta*'
        gpgcheck: true

    - name: Install Grafana package
      ansible.builtin.yum:
        name:
          - grafana

    - name: Enable and start grafana service
      ansible.builtin.service:
        name: grafana-server
        state: started
        enabled: true


- name: Deploy packages on TARGETS servers
  hosts: aap-demoeda-target*
  gather_facts: true
  become: true
  collections:
    - dynatrace.oneagent_deploy
  roles:
    - role: dynatrace.oneagent_deploy.oneagent
  vars:
    prometheus_url: 'https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz'
    oneagent_environment_url: "{{ dynatrace_environment_url }}"
    oneagent_paas_token: "{{ dynatrace_paas_token }}"
    oneagent_installer_arch: "x86"
    oneagent_package_state: latest


  tasks:

    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present

    - name: Add prometheus user to prometheus group
      ansible.builtin.user:
        name: prometheus
        groups: prometheus
        shell: /bin/bash&@
        state: present

    - name: Download Prometheus node_exporter binarie
      ansible.builtin.get_url:
        url: "{{ prometheus_url }}"
        dest: /tmp/node_exporter.tar.gz
        mode: '0440'
        owner: prometheus
        group: prometheus

    - name: Extract Prometheus node_exporter binarie to tmp directory
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Rename Prometheus directory
      ansible.builtin.shell: mv /tmp/node_exporter-* /tmp/node_exporter

    - name: Copy prometheus binaries to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/node_exporter/node_exporter
        dest: /usr/local/bin/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Copy prometheus node_exporter service file
      ansible.builtin.copy:
        src: templates/node_exporter.service
        dest: /etc/systemd/system/
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Enable and start node_exporter service
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: true

    - name: Delete temporary prometheus files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/node_exporter
        - /tmp/node_exporter.tar.gz
