---
- hosts: aap-demoeda-target*
  gather_facts: yes
  vars:
    - prometheus_url: 'https://github.com/prometheus/node_exporter/releases/download/v*/node_exporter-*.*-amd64.tar.gz'

  tasks:

    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present
 
    - name: Add prometheus user to prometheus group
      ansible.builtin.user:
        name: prometheus
        groups: prometheus
        shell: /bin/bash
        state: present

    - name: Download Prometheus node_exporter binarie
      ansible.builtin.get_url:
        url: "{{ prometheus_url }}"
        dest: /tmp/node_exporter.tar.gz
        mode: '0440'
        owner: prometheus
        group: prometheus

    - name: Extract Prometheus node_exporter binarie to tmp directory
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Rename Prometheus directory
      ansible.builtin.shell: mv /tmp/node_exporter-* /tmp/node_exporter

    - name: Copy prometheus binaries to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/node_exporter/node_exporter
        dest: /usr/local/bin/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Copy prometheus node_exporter service file
      ansible.builtin.copy:
        src: templates/node_exporter.service
        dest: /etc/systemd/system/
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Enable and start node_exporter service
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: true

    - name: Delete temporary prometheus files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/node_exporter
        - /tmp/node_exporter.tar.gz
