---
- hosts: aap-demoeda-sup.rhntnx.hpecic.net
  gather_facts: yes
  vars:
    - prometheus_url: 'https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz'
    - grafana_url: 'test'

  tasks:

    - name: Download Prometheus files
      ansible.builtin.get_url:
        url: "{{ prometheus_url }}"
        dest: /tmp/
        mode: '0440'
        owner: root
        group: root

