---
- hosts: aap-demoeda-sup.rhntnx.hpecic.net
  gather_facts: yes
  vars:
    - prometheus_url: 'https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz'
    - grafana_url: 'test'

  tasks:

    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present
 
    - name: Add prometheus user to prometheus group
      ansible.builtin.user:
        name: prometheus
        groups: prometheus
        shell: /bin/bash
        state: present

    - name: Create prometheus data directory
      ansible.builtin.file:
        path: /opt/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Create prometheus conf directory
      ansible.builtin.file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Download Prometheus binarie
      ansible.builtin.get_url:
        url: "{{ prometheus_url }}"
        dest: /tmp/prometheus.tar.gz   
        mode: '0440'
        owner: prometheus
        group: prometheus

    - name: Extract Prometheus binarie to tmp directory
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Rename Prometheus directory
      ansible.builtin.shell: mv /tmp/prometheus-* /tmp/prometheus

    - name: Copy prometheus binaries to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/prometheus/{{ item }}
        dest: /usr/local/bin/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'
      loop:
        - prometheus
        - promtool

    - name: Copy prometheus configuration file to /etc/prometheus
      ansible.builtin.copy:
        src: /tmp/prometheus/{{ item }}
        dest: /etc/prometheus/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: '0775'
      loop:
        - consoles
        - console_libraries

    - name: Copy prometheus config file
      ansible.builtin.copy:
        src: "templates/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0775'

    - name: Copy prometheus service file
      ansible.builtin.copy:
        src: templates/prometheus.service
        dest: /etc/systemd/system/
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Enable and start prometheus service
      ansible.builtin.service:
        name: prometheus
        state: started
        enabled: true

    - name: Delete temporary prometheus files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/prometheus
        - /tmp/prometheus.tar.gz
