apiVersion: tekton.dev/v1beta1
kind: Pipeline
spec:
  params:
    - default: 'https://github.com/davmartini/redhat-tech.git'
      description: Git repo url
      name: url
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/demo:latest
      description: Image destination url
      name: image
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:5b36e9d4ddffa4c253c47e444b7d3158bbbd2a3acf3c301389f6c50cbf5e8086
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: s2i-php
      params:
        - name: VERSION
          value: latest
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: $(params.image)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-php
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: false
  resources: []
  finally: []
