- hosts: localhost
  connection: local
  collections:
    - hpe.oneview

  vars:
    - ov_template:  Test_spt-1
    - enclosure_group_name: EG
    - server_hardware_type_name: SY 480 Gen9 2
#    - network_name: mgmt_nw
#    - server_profile_description: test
#    - inventory_hostname: sp1

  roles:
    - hpe.oneview.oneview_server_profile