---
- name: Leapp framework
  hosts: all
  gather_facts: true
  collections:
    - infra.leapp
  vars:
    leapp_upgrade_type: cdn
  roles:
    - role: infra.leapp.analysis
      when: (ansible_distribution == "RedHat") and (ansible_distribution_major_version < "9") 

