---
- name: Leapp framework
  hosts: all
  gather_facts: true
  collections:
    - infra.leapp
    - redhat.rhel_system_roles
  vars:
    leapp_upgrade_type: cdn
    cockpit_packages: 
      - cockpit
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-leapp
      - cockpit-system
    cockpit_enabled: true
    cockpit_started: true
    cockpit_port: 9090
  roles:
    - role: redhat.rhel_system_roles.cockpit
      when: (ansible_distribution == "RedHat") and (ansible_distribution_major_version < "9") 
    - role: infra.leapp.analysis
      when: (ansible_distribution == "RedHat") and (ansible_distribution_major_version < "9") 

