---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:
  
  - name: Log in to OpenShift
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      username: "{{ lookup('env', 'OCP_USERNAME') }}"
      password: "{{ lookup('env', 'OCP_PASSWORD') }}"
      validate_certs: false
    register: openshift_auth_results
 
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      host: "{{ lookup('env', 'OCP_URL') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: present
      name: testvm-with-dv
      namespace: vms
      labels:
        app: rhel-in-place-upgrade
      instancetype:
        name: u1.small
      preference:
        name: rhel.8
      data_volume_templates:
        - metadata:
            name: testvm-with-dv
          spec:
            source:
              registry:
                url: docker://registry.redhat.io/rhel8/rhel-guest-image:latest
            storage:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
      spec:
        domain:
          devices: {}
        volumes:
        - dataVolume:
            name: testdv
          name: datavolume
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              # The default username is: cloud-user
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3OL8vJoTsbn/LBUZWgV8YYmxUZSMAWZ6UKMHC2iF9VCYmuI0opJKNBpEDFlomrENOm7HkEIafdPpFfEiDMszDhskvNWAVPiJJChjMBxFgvNWLAEHJQKvGaylVDF4yOex9ehMKOnhBVnO7FFrn33AmgiikEQRcqkz9Q1NQ7ccDZzF5eml0brxmO+2IziUrPdeVwkR7Wzw19zyxLf3f7dfGkfnfoeku1D8BWQaclN0T8AAC4IAVQ1YXp5kf4rpPdf3eCMUKItJCwW4nAKLmJDoJTMXx6LsOGsBZHwPxV0LbR9titUhGpRCBor2nYs1EnN4qCd7f+3yU0lZ+dV5HdMWXesD2czEY8CTncEhD+6c4x3RnyLNC+zqHuM4U1szsQPkOxI5zqItxVgy0HmLThpaA0knohTVYAnq+Qhw+iA6yokRv/pBRTr9fPeUv03LBB5tYEhBDCkGICY4ZRuT+NlsBHMxAjeQIIYeOh0DwldEl2QXVJc3eNt5nkQw49BoCGIU= dmartini@Davids-MacBook-Pro
          name: cloudinit
      wait: yes

  - name: Log out to OpenShift
    when: openshift_auth_results.openshift_auth.api_key is defined
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: absent
