---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:
  
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
      api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
      validate_certs: false
      state: present
      name: testvm-with-dv
      namespace: vms
      labels:
        app: rhel-in-place-upgrade
      instancetype:
        name: u1.small
      preference:
        name: rhel.8
      data_volume_templates:
        - metadata:
            name: testvm-with-dv-pvc
          spec:
            source:
              registry:
                url: docker://quay.io/containerdisks/fedora:latest
            storage:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
      spec:
        domain:
          devices: {}
        accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              configDrive: {}
        volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:latest
          name: containerdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              # The default username is: cloud-user
          name: cloudinit
      wait: yes
