---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:
  
  - name: Log in to OpenShift
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      username: "{{ lookup('env', 'OCP_USERNAME') }}"
      password: "{{ lookup('env', 'OCP_PASSWORD') }}"
      validate_certs: false
    register: openshift_auth_results
 
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      host: "{{ lookup('env', 'OCP_URL') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: present
      name: testvm-with-dv
      namespace: vms
      labels:
        app: rhel-in-place-upgrade
      instancetype:
        name: u1.small
      preference:
        name: rhel.8
      data_volume_templates:
      - metadata:
          name: rhel8
        spec:
          sourceRef:
            kind: DataSource
            name: rhel8
            namespace: openshift-virtualization-os-images
          storage:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
      spec:
        domain:
          devices: {}
        accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              configDrive: {}
        volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:latest
          name: containerdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              # The default username is: cloud-user
          name: cloudinit
      wait: yes

  - name: Log out to OpenShift
    when: openshift_auth_results.openshift_auth.api_key is defined
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: absent
