---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:
  
  - name: Log in to OpenShift
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      username: "{{ lookup('env', 'OCP_USERNAME') }}"
      password: "{{ lookup('env', 'OCP_PASSWORD') }}"
      validate_certs: false
    register: openshift_auth_results
 
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      host: "{{ lookup('env', 'OCP_URL') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: present
      name: testvm-with-dv
      namespace: vms
      labels:
        app: rhel-in-place-upgrade
      instancetype:
        name: u1.medium
      preference:
        name: fedora
      data_volume_templates:
        - metadata:
            name: testdv
          spec:
            source:
              registry:
                url: docker://quay.io/containerdisks/fedora:latest
            storage:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
      spec:
        domain:
          devices: {}
        volumes:
        - dataVolume:
            name: testdv
          name: datavolume
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              # The default username is: fedora
              ssh_authorized_keys:
                - ssh-ed25519 AAAA...
          name: cloudinit
      wait: yes

  - name: Log out to OpenShift
    when: openshift_auth_results.openshift_auth.api_key is defined
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: absent
