---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:
  
  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
      state: present
      name: testvm-with-dv
      namespace: vms
      labels:
        app: rhel-in-place-upgrade
      instancetype:
        name: u1.small
      preference:
        name: rhel.8
      data_volume:
      - metadata:
          name: rhel8
        spec:
          source:
            pvc:
              name: rhel8-2cde3f47f8c7
              namespace: openshift-virtualization-os-images
          storage:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
      spec:
        domain:
          devices: {}
        accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              configDrive: {}
        volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:latest
          name: containerdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              # The default username is: cloud-user
          name: cloudinit
      wait: yes
