---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local

  tasks:

  - name: Log in to OpenShift
    redhat.openshift.openshift_auth:
      username: "{{ openshift_admin_user }}"
      password: "{{ openshift_admin_password }}"
    register: openshift_auth_results

  - name: Print openshift_auth_resuslts
    ansible.builtin.debug:
      msg: "{{ openshift_auth_results }}" 

  - name: Create VM on KubeVirt
    kubevirt.core.kubevirt_vm:
      state: present
      name: testvm
      namespace: vms
      labels:
        app: in-place-upgrade
      instancetype:
        name: u1.medium
      preference:
        name: rhel7
      spec:
        domain:
          devices:
            interfaces:
            - name: default
              masquerade: {}
        networks:
        - name: default
          pod: {}
        accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              configDrive: {}
        volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:latest
          name: containerdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              # The default username is: cloud-user
          name: cloudinit
      wait: yes