---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:
  
  - name: Set vars
    set_fact:
      uuid: "{{ 1000 | random }}"
      os_template: "{{ 'rhel.7' if os == 'rhel7' else 'rhel.8' if os == 'rhel8' else 'rhel.9' if os == 'rhel9' }}"
    run_once: yes

  - name: Create a VirtualMachine with a DataVolume template
    kubevirt.core.kubevirt_vm:
      host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
      api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
      validate_certs: false
      state: present
      name: "{{ topic }}-{{ uuid }}{{ item }}"
      namespace: vms-demo
      labels:
        app: "{{ topic }}"
      instancetype:
        name: "{{ flavor }}"
      preference:
        name: "{{ os_template }}"
      data_volume_templates:
        - metadata:
            name: "{{ topic }}-{{ uuid }}{{ item }}-dv"
          spec:
            sourceRef:
              kind: DataSource
              name: "{{ os }}"
              namespace: openshift-virtualization-os-images
            storage:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 30Gi
              storageClassName: lvms-vg1
      spec:
        domain:
          devices: {}
        accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              configDrive: {}
        volumes:
        - dataVolume:
            name: "{{ topic }}-{{ uuid }}{{ item }}-dv"
          name: datavolume
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              # The default username is: cloud-user
          name: cloudinit
      wait: yes
    loop: "{{ range(0, vm_number|int)|list}}"