---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local

  tasks:
  
  - name: Log in to OpenShift
    redhat.openshift.openshift_auth:
      host: "{{ lookup('env', 'OCP_URL') }}"
      username: "{{ lookup('env', 'OCP_USERNAME') }}"
      password: "{{ lookup('env', 'OCP_PASSWORD') }}"
      validate_certs: false
    register: openshift_auth_results

  - name: Delete a VirtualMachine
    kubevirt.core.kubevirt_vm:
      name: testvm
      namespace: vms
      state: absent

  - name: Log out to OpenShift
    when: openshift_auth_results.openshift_auth.api_key is defined
    redhat.openshift.openshift_auth:
      state: absent
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
