---
- name: create VM on OpenShift Virt
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - redhat.openshift
    - kubevirt.core

  tasks:

    - name: List VMs on OpenShift Virtualization
      kubevirt.core.kubevirt_vm_info:
        host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
        api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
        validate_certs: false
        namespace: vms-demo
      register: result
    
    - name: Set list vms by name
      ansible.builtin.set_fact:
        vms_list: "{{ result | json_query('resources[*].metadata.name') }}"

    - name: Print listed VMs
      ansible.builtin.debug:
          var: vms_list