apiVersion: velero.io/v1
kind: Backup
metadata:
  name: demo-backup-01
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - demo
  excludedResources:
  - build.build.openshift.io
  - replicationcontroller
  - pods
  - serving.knative.dev