apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jndi-exploit-kit
    app.kubernetes.io/component: jndi-exploit-kit
    app.kubernetes.io/instance: jndi-exploit-kit
  name: jndi-exploit-kit
  namespace: exploitkit-log4j
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: jndi-exploit-kit
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: jndi-exploit-kit
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc.cluster.local:5000/vulnerable-cicd/exploitkit-log4j:latest
        imagePullPolicy: Always
        name: jndi-exploit-kit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
