apiVersion: v1
kind: Service
metadata:
  labels:
    app: jndi-exploit-kit
  name: jndi-exploit-kit
  namespace: exploitkit-log4j
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ldap
    port: 1389
    protocol: TCP
    targetPort: 1389
  - name: rmi
    port: 1099
    protocol: TCP
    targetPort: 1099
  selector:
    deployment: jndi-exploit-kit
  sessionAffinity: None
  type: ClusterIP
