kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nutanix-volume
  volumeMode: Filesystem
