apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    name.os.template.kubevirt.io/rhel9.0: Win2K19 or higher
  name: win-bdd-sqlserver01
  labels:
    app: mix-app
    flavor.template.kubevirt.io/small: 'true'
    os.template.kubevirt.io/rhel9.0: 'true'
    vm.kubevirt.io/template: windows2k19-server-medium
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.19.6
    workload.template.kubevirt.io/server: 'true'
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: win-bdd-sqlserver01
      spec:
        source:
          pvc:
            name: win2k19
            namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
          storageClassName: odf-lvm-vg1
          volumeMode: Filesystem
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: win2k19
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        flavor.template.kubevirt.io/small: 'true'
        kubevirt.io/domain: win-bdd-sqlserver01
        kubevirt.io/size: small
        os.template.kubevirt.io/rhel9.0: 'true'
        vm.kubevirt.io/name: win-bdd-sqlserver01
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: sata
              name: win-bdd-sqlserver01
          interfaces:
            - masquerade: {}
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 4Gi
      evictionStrategy: LiveMigrate
      hostname: win-bdd-sqlserver01
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: win-bdd-sqlserver01
          name: win-bdd-sqlserver01