---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: echo env 
      shell: echo env
      register: env

    - name: print env
      debug:
        msg: "{{ env.stdout }}"

    - name: VM with rhel-8-cloud-init image
      nutanix.ncp.ntnx_vms:
        state: present
        name: testvm
        timezone: "UTC"
        validate_certs: False
        cluster:
          name: "PHX-POC169"
        disks:
          - type: "DISK"
            size_gb: 10
            clone_image:
              name:  "rhel-8.5-update-2-x86_64-kvm.qcow2"
            bus: "SCSI"
