---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: Create Nutanix VM
      nutanix.ncp.ntnx_vms:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        state: present
        name: "dev_vm_{{ uuid }}"
        timezone: "UTC"
        validate_certs: False
        cluster:
          name: "ntnx-cluster-hpe-cic"
        networks:
          - is_connected: True
            subnet:
              name: "workload"
        disks:
          - type: "DISK"
            size_gb: 10
            clone_image:
              name:  "rhel-8.7-x86_64-kvm.qcow2"
            bus: "SCSI"
        vcpus: "{{ nb_cpu }}"
        cores_per_vcpu: 1
        memory_gb: "{{ nb_mem }}"
        guest_customization:
          type: "cloud_init"
          script_path: "cloud_init_dev.yml"
          is_overridable: False
      vars:
        uuid: "{{ 9999 | random }}"
      loop: "{{ range(0, vm_number|int)|list}}"