---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: VM with rhel-8-cloud-init image
      nutanix.ncp.ntnx_vms:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        state: present
        name: "dev_vm_{{ uuid }}"
        timezone: "UTC"
        validate_certs: False
        cluster:
          name: "ntnx-cluster-hpe-cic"
        disks:
          - type: "DISK"
            size_gb: 10
            clone_image:
              name:  "rhel-8.7-x86_64-kvm.qcow2"
            bus: "SCSI"
      vars:
        uuid: "{{ 9999 | random }}"
      loop: "{{ range(0, vm_number|int)|list}}"