---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: List VMs on Nutanix
      nutanix.ncp.ntnx_vms_info:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: False
        sort_order: "ASCENDING"
        sort_attribute: "vm_name"
      register: vms

    - name: Set list vms
      ansible.builtin.set_fact:
        vms_list: "{{ vms.response | json_query('entities[*].status.name') }}"

    - name: Delete Nutanix VMs
      nutanix.ncp.ntnx_vms:
        state: absent
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ _nutanix_password_ }}"
        validate_certs: false
        name: "{{ item }}"       
      with_items: "{{ vms_list }}"
      when: '"dev" in item'