---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: List VMs on Nutanix
      nutanix.ncp.ntnx_vms_info:
      register: vms

    - name: Print vms
      ansible.builtin.debug:
        msg: "{{ vms }}"
