---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: List VMs on Nutanix
      nutanix.ncp.ntnx_vms_info:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: False
      register: vms

    - name: Set list vms by name
      ansible.builtin.set_fact:
        vms_list: "{{ vms.response | json_query('entities[*].status.ressources.bios_uuid') }}"

    - name: Print VMs
      ansible.builtin.debug:
        var: vms_list