---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: List VMS using length, offset, sort order and vm_name sort attribute
      ntnx_vms_info:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: False
        filter:
            vm_name: "dev-demo-4121"
        kind: vm
      register: vm_creation


    - name: Register the created vm uuid's for future use
      set_fact:
        uuids: "{{ item.json.metadata.uuid }}"
      with_items: "{{ vm_creation.results }}"
      register: vm_uuid

    - name: print
      debug:
        msg: "{{ vm_uuid }}"

    - name: Delete VM
      ntnx_vms:
        state: absent
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: False
        vm_uuid: "{{result.uuid}}"