---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp

  tasks:

    - name: List VMs on Nutanix
      nutanix.ncp.ntnx_vms_info:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: False
        sort_order: "ASCENDING"
        sort_attribute: "vm_name"
      register: vms

    - name: Print vms
      ansible.builtin.debug:
        msg: "{{ vms.response.entities.status.name }}"