---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - nutanix.ncp
  vars:
    nutanix_host: "{{ nutanix_host }}"
    nutanix_username: "{{ nutanix_username }}"
    nutanix_password: "{{ nutanix_password }}"
    validate_certs: False

  tasks:

    - name: List VMs on Nutanix
      nutanix.ncp.ntnx_vms_info:
      register: vms

    - name: Print vms
      ansible.builtin.debug:
        msg: "{{ vms }}"
