kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-db-oadp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
